import type { Tender, CompanyProfile, UploadedFile } from './types';

export const companyProfile: CompanyProfile = {
  name: 'TechVision Solutions Pvt Ltd',
  industries: ['IT & Software', 'Construction', 'Consultancy'],
  location: 'Islamabad',
  budgetRange: 'PKR 5M – 50M',
};

export const initialUploadedFiles: UploadedFile[] = [
  { id: 'f1', name: 'NTN_Certificate.pdf', size: 245678, type: 'application/pdf', uploadDate: '2026-09-28' },
  { id: 'f2', name: 'Company_Registration.pdf', size: 512000, type: 'application/pdf', uploadDate: '2026-09-28' },
  { id: 'f3', name: 'Financial_Statement_2025.pdf', size: 1843200, type: 'application/pdf', uploadDate: '2026-09-29' },
  { id: 'f4', name: 'ISO_9001_Certificate.pdf', size: 387200, type: 'application/pdf', uploadDate: '2026-09-30' },
];

export const mockTenders: Tender[] = [
  {
    id: 't1',
    title: 'Supply, Installation & Maintenance of Enterprise Network Infrastructure',
    organization: 'Pakistan Telecommunication Company Ltd (PTCL)',
    industry: 'IT & Software',
    location: 'Islamabad',
    budget: 45000000,
    budgetLabel: 'PKR 45.0M',
    deadline: '2026-10-15',
    daysLeft: 13,
    matchPercentage: 92,
    category: 'Goods & Services',
    description:
      'PTCL invites bids from pre-qualified firms for the supply, installation, and ongoing maintenance of enterprise-grade network infrastructure across 12 regional offices. The scope includes routers, switches, firewalls, UPS systems, cabling, and a 3-year maintenance contract with 24/7 support SLA.',
    eligibilityStatus: 'eligible',
    aiSummary:
      'This tender is an excellent match for TechVision Solutions. Your company meets all core eligibility criteria including valid NTN, ISO 9001 certification, and relevant prior experience in enterprise networking projects. The budget falls well within your operational range. Only one minor document (bid security) is outstanding — uploading it will push your match to 96%+.',
    referenceNo: 'PTCL/IT/2026/0457',
    publishedDate: '2026-09-20',
    requirements: [
      { id: 'r1', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r2', label: 'ISO 9001 Certification', matched: true, category: 'Quality' },
      { id: 'r3', label: 'Minimum 5 years enterprise networking experience', matched: true, category: 'Experience' },
      { id: 'r4', label: 'Annual turnover ≥ PKR 100M', matched: true, category: 'Financial' },
      { id: 'r5', label: 'Bid security (2% of contract value)', matched: false, category: 'Financial' },
      { id: 'r6', label: 'At least 3 similar completed projects', matched: true, category: 'Experience' },
      { id: 'r7', label: 'Registered with PSEB', matched: true, category: 'Legal' },
      { id: 'r8', label: 'Manufacturer authorization letter', matched: false, category: 'Documentation' },
    ],
    documents: [
      { id: 'd1', name: 'Tender Notice (NIT).pdf', required: true },
      { id: 'd2', name: 'Technical Specifications.pdf', required: true },
      { id: 'd3', name: 'BOQ – Bill of Quantities.xlsx', required: true },
      { id: 'd4', name: 'Eligibility Criteria.pdf', required: true },
      { id: 'd5', name: 'Bid Submission Form.docx', required: true },
      { id: 'd6', name: 'Evaluation Matrix.pdf', required: false },
    ],
  },
  {
    id: 't2',
    title: 'Development of Citizen Portal Mobile Application (iOS & Android)',
    organization: 'National Information Technology Board (NITB)',
    industry: 'IT & Software',
    location: 'Islamabad',
    budget: 28000000,
    budgetLabel: 'PKR 28.0M',
    deadline: '2026-10-10',
    daysLeft: 8,
    matchPercentage: 88,
    category: 'Services',
    description:
      'NITB seeks a qualified software firm to design, develop, and deploy a cross-platform Citizen Portal mobile application for iOS and Android. The app will provide citizens access to government services, complaint registration, tracking, and notifications. Includes 12 months of post-launch maintenance.',
    eligibilityStatus: 'eligible',
    aiSummary:
      'Strong alignment with your software development expertise. You meet 7 of 8 requirements. The missing item is a PSEB membership renewal — if renewed before the deadline, your match would exceed 90%. Budget is within range and the timeline is comfortable for your team size.',
    referenceNo: 'NITB/MOB/2026/0112',
    publishedDate: '2026-09-18',
    requirements: [
      { id: 'r1', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r2', label: 'PSEB Registration (active)', matched: false, category: 'Legal' },
      { id: 'r3', label: 'Minimum 3 mobile app projects delivered', matched: true, category: 'Experience' },
      { id: 'r4', label: 'Team includes certified iOS & Android developers', matched: true, category: 'Technical' },
      { id: 'r5', label: 'Annual turnover ≥ PKR 50M', matched: true, category: 'Financial' },
      { id: 'r6', label: 'ISO 27001 (Information Security)', matched: true, category: 'Quality' },
      { id: 'r7', label: 'UX/UI design portfolio', matched: true, category: 'Experience' },
      { id: 'r8', label: 'Bid security (2% of contract value)', matched: true, category: 'Financial' },
    ],
    documents: [
      { id: 'd1', name: 'Tender Notice (RFP).pdf', required: true },
      { id: 'd2', name: 'Technical Scope & SOW.pdf', required: true },
      { id: 'd3', name: 'Evaluation Criteria.pdf', required: true },
      { id: 'd4', name: 'Contract Draft.pdf', required: false },
      { id: 'd5', name: 'Data Protection Requirements.pdf', required: true },
    ],
  },
  {
    id: 't3',
    title: 'Construction of District Headquarters Hospital – Phase II',
    organization: 'Provincial Health Department, Punjab',
    industry: 'Construction',
    location: 'Lahore',
    budget: 850000000,
    budgetLabel: 'PKR 850.0M',
    deadline: '2026-10-22',
    daysLeft: 20,
    matchPercentage: 45,
    category: 'Works',
    description:
      'Civil works for the construction of a 250-bed District Headquarters Hospital including outpatient block, inpatient wards, operation theaters, diagnostic wing, pharmacy, and administrative block. Includes MEP, HVAC, medical gas pipeline, and external development works.',
    eligibilityStatus: 'not-eligible',
    aiSummary:
      'This tender is not a good match for TechVision Solutions. Your company profile is in IT & Software, while this is a large-scale civil construction project requiring a Category C-1 contractor license from PEC, which you do not possess. The budget far exceeds your typical range. Consider partnering with a civil construction firm if you wish to pursue the IT/low-current subsystems portion.',
    referenceNo: 'PHD/WORKS/2026/0339',
    publishedDate: '2026-09-15',
    requirements: [
      { id: 'r1', label: 'PEC Registration Category C-1 (Civil)', matched: false, category: 'Legal' },
      { id: 'r2', label: 'Minimum 10 years civil construction experience', matched: false, category: 'Experience' },
      { id: 'r3', label: 'Completed hospital project ≥ PKR 500M', matched: false, category: 'Experience' },
      { id: 'r4', label: 'Annual turnover ≥ PKR 1 Billion', matched: false, category: 'Financial' },
      { id: 'r5', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r6', label: 'Bid security (5% of contract value)', matched: false, category: 'Financial' },
      { id: 'r7', label: 'OHSAS 18001 / ISO 45001 Certification', matched: false, category: 'Quality' },
      { id: 'r8', label: 'Plant & machinery declaration', matched: false, category: 'Technical' },
    ],
    documents: [
      { id: 'd1', name: 'Tender Notice (NIT).pdf', required: true },
      { id: 'd2', name: 'Drawings & BOQ.pdf', required: true },
      { id: 'd3', name: 'Technical Specifications.pdf', required: true },
      { id: 'd4', name: 'Contract Conditions.pdf', required: true },
      { id: 'd5', name: 'Bid Form.docx', required: true },
      { id: 'd6', name: 'Site Map.pdf', required: false },
    ],
  },
  {
    id: 't4',
    title: 'Cloud Migration & Digital Transformation Consulting Services',
    organization: 'State Bank of Pakistan (SBP)',
    industry: 'Consultancy',
    location: 'Karachi',
    budget: 35000000,
    budgetLabel: 'PKR 35.0M',
    deadline: '2026-10-18',
    daysLeft: 16,
    matchPercentage: 85,
    category: 'Services',
    description:
      'SBP requires consulting services for a comprehensive cloud migration strategy and digital transformation roadmap. The engagement includes assessment of current IT infrastructure, cloud architecture design, security compliance review, vendor selection support, and a phased migration plan aligned with international banking standards.',
    eligibilityStatus: 'eligible',
    aiSummary:
      'Good match for your consultancy capabilities. You meet 6 of 8 requirements. Missing items are a banking-sector project reference and an active PEC registration (optional but preferred). Your cloud certifications and prior digital transformation work are strong differentiators.',
    referenceNo: 'SBP/CONS/2026/0078',
    publishedDate: '2026-09-22',
    requirements: [
      { id: 'r1', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r2', label: 'ISO 9001 Certification', matched: true, category: 'Quality' },
      { id: 'r3', label: 'Minimum 5 years consulting experience', matched: true, category: 'Experience' },
      { id: 'r4', label: 'Banking/financial sector project reference', matched: false, category: 'Experience' },
      { id: 'r5', label: 'Cloud certifications (AWS/Azure/GCP)', matched: true, category: 'Technical' },
      { id: 'r6', label: 'Annual turnover ≥ PKR 80M', matched: true, category: 'Financial' },
      { id: 'r7', label: 'PEC Registration (preferred)', matched: false, category: 'Legal' },
      { id: 'r8', label: 'ISO 27001 Certification', matched: true, category: 'Quality' },
    ],
    documents: [
      { id: 'd1', name: 'RFP Document.pdf', required: true },
      { id: 'd2', name: 'Scope of Work.pdf', required: true },
      { id: 'd3', name: 'Evaluation Criteria.pdf', required: true },
      { id: 'd4', name: 'TOR – Terms of Reference.pdf', required: true },
      { id: 'd5', name: 'Non-Disclosure Agreement.pdf', required: false },
    ],
  },
  {
    id: 't5',
    title: 'Supply of Medical Equipment for Rural Health Centers',
    organization: 'Ministry of National Health Services',
    industry: 'Healthcare',
    location: 'Islamabad',
    budget: 120000000,
    budgetLabel: 'PKR 120.0M',
    deadline: '2026-10-08',
    daysLeft: 6,
    matchPercentage: 38,
    category: 'Goods',
    description:
      'Supply and installation of medical equipment including ultrasound machines, patient monitors, autoclaves, and lab analyzers for 40 rural health centers across Pakistan. Includes training, warranty, and 2-year after-sales support.',
    eligibilityStatus: 'not-eligible',
    aiSummary:
      'Poor match. This is a medical equipment supply tender requiring DRAP registration and healthcare-specific certifications that TechVision Solutions does not hold. Your IT and construction profile does not align with medical goods procurement. Not recommended.',
    referenceNo: 'MNHS/SUP/2026/0204',
    publishedDate: '2026-09-19',
    requirements: [
      { id: 'r1', label: 'DRAP Registration (Drug Regulatory Authority)', matched: false, category: 'Legal' },
      { id: 'r2', label: 'Medical device distribution license', matched: false, category: 'Legal' },
      { id: 'r3', label: 'Minimum 5 years medical equipment supply', matched: false, category: 'Experience' },
      { id: 'r4', label: 'Annual turnover ≥ PKR 300M', matched: false, category: 'Financial' },
      { id: 'r5', label: 'Manufacturer authorization letters', matched: false, category: 'Documentation' },
      { id: 'r6', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r7', label: 'ISO 13485 (Medical Devices QMS)', matched: false, category: 'Quality' },
      { id: 'r8', label: 'After-sales service infrastructure', matched: false, category: 'Technical' },
    ],
    documents: [
      { id: 'd1', name: 'Tender Notice.pdf', required: true },
      { id: 'd2', name: 'Equipment List & Specs.pdf', required: true },
      { id: 'd3', name: 'BOQ.xlsx', required: true },
      { id: 'd4', name: 'Delivery Schedule.pdf', required: true },
    ],
  },
  {
    id: 't6',
    title: 'ERP System Implementation for Water & Power Development Authority',
    organization: 'WAPDA',
    industry: 'IT & Software',
    location: 'Lahore',
    budget: 62000000,
    budgetLabel: 'PKR 62.0M',
    deadline: '2026-10-25',
    daysLeft: 23,
    matchPercentage: 90,
    category: 'Services',
    description:
      'WAPDA seeks a qualified firm for end-to-end ERP system implementation covering finance, HR, inventory, procurement, and project management modules. The scope includes system design, customization, data migration, integration with existing systems, training, and 24 months of post-go-live support.',
    eligibilityStatus: 'eligible',
    aiSummary:
      'Excellent match. You meet 7 of 8 requirements for this ERP implementation tender. Your prior experience with enterprise software deployments and relevant certifications make you a strong candidate. The only gap is a bid security document, which is a standard submission item you can arrange quickly.',
    referenceNo: 'WAPDA/ERP/2026/0167',
    publishedDate: '2026-09-23',
    requirements: [
      { id: 'r1', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r2', label: 'ISO 9001 Certification', matched: true, category: 'Quality' },
      { id: 'r3', label: 'Minimum 5 years ERP implementation experience', matched: true, category: 'Experience' },
      { id: 'r4', label: 'At least 2 ERP projects ≥ PKR 50M', matched: true, category: 'Experience' },
      { id: 'r5', label: 'Annual turnover ≥ PKR 150M', matched: true, category: 'Financial' },
      { id: 'r6', label: 'Certified ERP consultants on team', matched: true, category: 'Technical' },
      { id: 'r7', label: 'PSEB Registration (active)', matched: true, category: 'Legal' },
      { id: 'r8', label: 'Bid security (2% of contract value)', matched: false, category: 'Financial' },
    ],
    documents: [
      { id: 'd1', name: 'Tender Notice (RFP).pdf', required: true },
      { id: 'd2', name: 'Functional Requirements.pdf', required: true },
      { id: 'd3', name: 'Technical Architecture Specs.pdf', required: true },
      { id: 'd4', name: 'Evaluation Criteria.pdf', required: true },
      { id: 'd5', name: 'Support & Maintenance SLA.pdf', required: false },
      { id: 'd6', name: 'Data Migration Plan Template.docx', required: true },
    ],
  },
  {
    id: 't7',
    title: 'Security Audit & Penetration Testing of Government Web Portals',
    organization: 'Ministry of IT & Telecommunication (MoITT)',
    industry: 'IT & Software',
    location: 'Islamabad',
    budget: 15000000,
    budgetLabel: 'PKR 15.0M',
    deadline: '2026-10-12',
    daysLeft: 10,
    matchPercentage: 95,
    category: 'Services',
    description:
      'MoITT requires comprehensive security audits and penetration testing of 25 government web portals and citizen-facing applications. The scope includes vulnerability assessment, penetration testing (web + API), code review, remediation recommendations, and a re-test cycle.',
    eligibilityStatus: 'eligible',
    aiSummary:
      'Outstanding match at 95%. Your company meets all eligibility criteria for this cybersecurity engagement. Your ISO 27001 certification, OSCP-certified team members, and prior government security audit experience make you a top candidate. All required documents are in place.',
    referenceNo: 'MoITT/SEC/2026/0091',
    publishedDate: '2026-09-25',
    requirements: [
      { id: 'r1', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r2', label: 'ISO 27001 Certification', matched: true, category: 'Quality' },
      { id: 'r3', label: 'OSCP / CEH certified team members', matched: true, category: 'Technical' },
      { id: 'r4', label: 'Minimum 3 years security audit experience', matched: true, category: 'Experience' },
      { id: 'r5', label: 'At least 5 penetration testing projects', matched: true, category: 'Experience' },
      { id: 'r6', label: 'PSEB Registration (active)', matched: true, category: 'Legal' },
      { id: 'r7', label: 'Government sector clearance (optional)', matched: true, category: 'Legal' },
      { id: 'r8', label: 'Bid security (2% of contract value)', matched: true, category: 'Financial' },
    ],
    documents: [
      { id: 'd1', name: 'Tender Notice (TOR).pdf', required: true },
      { id: 'd2', name: 'Scope of Work.pdf', required: true },
      { id: 'd3', name: 'List of Portals.xlsx', required: true },
      { id: 'd4', name: 'Reporting Format.pdf', required: true },
      { id: 'd5', name: 'NDA Template.pdf', required: false },
    ],
  },
  {
    id: 't8',
    title: 'Solar Power Installation for Government Buildings – Sindh',
    organization: 'Energy Department, Government of Sindh',
    industry: 'Energy',
    location: 'Karachi',
    budget: 320000000,
    budgetLabel: 'PKR 320.0M',
    deadline: '2026-10-30',
    daysLeft: 28,
    matchPercentage: 28,
    category: 'Works',
    description:
      'Design, supply, installation, and commissioning of grid-tied solar PV systems (total 5MW) across 18 government buildings in Sindh. Includes structural work, inverters, net metering, SCADA monitoring, and 5-year O&M.',
    eligibilityStatus: 'not-eligible',
    aiSummary:
      'Not a match. This is an energy sector EPC tender requiring AEDB-certified installers and electrical engineering licenses that your IT-focused company does not hold. The project scale and sector are outside your profile.',
    referenceNo: 'EDS/SOL/2026/0145',
    publishedDate: '2026-09-21',
    requirements: [
      { id: 'r1', label: 'AEDB Certified Installer License', matched: false, category: 'Legal' },
      { id: 'r2', label: 'PEC Registration Category E-1 (Electrical)', matched: false, category: 'Legal' },
      { id: 'r3', label: 'Minimum 10 MW solar installation experience', matched: false, category: 'Experience' },
      { id: 'r4', label: 'Annual turnover ≥ PKR 500M', matched: false, category: 'Financial' },
      { id: 'r5', label: 'Valid NTN Registration', matched: true, category: 'Legal' },
      { id: 'r6', label: 'ISO 9001 Certification', matched: true, category: 'Quality' },
      { id: 'r7', label: 'O&M team with certified electricians', matched: false, category: 'Technical' },
      { id: 'r8', label: 'Bid security (5% of contract value)', matched: false, category: 'Financial' },
    ],
    documents: [
      { id: 'd1', name: 'Tender Notice.pdf', required: true },
      { id: 'd2', name: 'Technical Specs.pdf', required: true },
      { id: 'd3', name: 'BOQ.xlsx', required: true },
      { id: 'd4', name: 'Site Survey Reports.pdf', required: false },
    ],
  },
];

export const industries = ['All Industries', 'IT & Software', 'Construction', 'Consultancy', 'Healthcare', 'Energy'];
export const locations = ['All Locations', 'Islamabad', 'Lahore', 'Karachi', 'Multan', 'Peshawar'];
export const budgetRanges = [
  'All Budgets',
  'Under PKR 20M',
  'PKR 20M – 50M',
  'PKR 50M – 100M',
  'PKR 100M – 500M',
  'Over PKR 500M',
];
